// Registro de íconos lucide de la plataforma (equivalente a lib/icons.ts del
// React). Se proveen una sola vez en app.config y cada componente usa
// <lucide-icon name="..."> con el nombre kebab-case.

import {
  ArrowLeft,
  BarChart3,
  Bell,
  Brain,
  Calculator,
  CalendarCheck,
  ChevronDown,
  Cloud,
  Construction,
  ExternalLink,
  FileText,
  FolderOpen,
  Gem,
  HelpCircle,
  Home,
  LayoutGrid,
  LogOut,
  Moon,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  User,
  Wallet,
} from 'lucide-angular';

export const ALMA_ICONS = {
  ArrowLeft,
  BarChart3,
  Bell,
  Brain,
  Calculator,
  CalendarCheck,
  ChevronDown,
  Cloud,
  Construction,
  ExternalLink,
  FileText,
  FolderOpen,
  Gem,
  HelpCircle,
  Home,
  LayoutGrid,
  LogOut,
  Moon,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  User,
  Wallet,
};
